/* tslint:disable */
/* eslint-disable */
/**
 * TupBayiProje HTTP API
 * TBP-21 contract temeli. Onayli endpoint\'ler kendi Jira islerinde eklenir.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { Hata, SistemSaglik } from "../models/index";
import {
  HataFromJSON,
  HataToJSON,
  SistemSaglikFromJSON,
  SistemSaglikToJSON,
} from "../models/index";

/**
 *
 */
export class SystemApi extends runtime.BaseAPI {
  /**
   * API platform durumunu getirir
   */
  async getSystemHealthRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SistemSaglik>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/v1/system/health`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SistemSaglikFromJSON(jsonValue),
    );
  }

  /**
   * API platform durumunu getirir
   */
  async getSystemHealth(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SistemSaglik> {
    const response = await this.getSystemHealthRaw(initOverrides);
    return await response.value();
  }
}
