// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TupBayiProje.Moduller.Audit.Altyapi;

#nullable disable

namespace TupBayiProje.Moduller.Audit.Altyapi.Migrations
{
    [DbContext(typeof(DenetimVeritabaniBaglami))]
    [Migration("20261010101916_AuditIlkSema")]
    partial class AuditIlkSema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("master")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TupBayiProje.Moduller.Audit.Altyapi.DenetimKaydi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CorrelationKimligi")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("GerekceKodu")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gerekce_kodu");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("islem");

                    b.Property<Guid>("KararKimligi")
                        .HasColumnType("uuid")
                        .HasColumnName("karar_id");

                    b.Property<DateTimeOffset>("OlusturulmaZamani")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("olusturulma_zamani")
                        .HasDefaultValueSql("statement_timestamp()");

                    b.Property<string>("ServisKimligi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("servis_kimligi")
                        .HasDefaultValueSql("current_user");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sonuc");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_denetim_kaydi");

                    b.HasIndex("KararKimligi")
                        .IsUnique()
                        .HasDatabaseName("ux_denetim_kaydi_karar_id");

                    b.ToTable("denetim_kaydi", "master", t =>
                        {
                            t.HasCheckConstraint("ck_denetim_kaydi_islem", "islem = 'TENANT_SECRET_OKUMA_KARARI'");

                            t.HasCheckConstraint("ck_denetim_kaydi_servis_kimligi", "servis_kimligi = 'audit_runtime'");

                            t.HasCheckConstraint("ck_denetim_kaydi_sonuc_gerekce", "(sonuc = 'IZIN_VERILDI' AND gerekce_kodu IS NULL) OR (sonuc = 'REDDEDILDI' AND gerekce_kodu IS NOT NULL AND gerekce_kodu IN ('ERISIM_REDDEDILDI', 'METADATA_GECERSIZ', 'SECRET_BULUNAMADI', 'SECRET_SAGLAYICI_ERISILEMIYOR'))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
