<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>TupBayiProje.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Moduller\Audit\Altyapi\TupBayiProje.Moduller.Audit.Altyapi.csproj" />
    <ProjectReference Include="..\..\Moduller\Tenancy\Altyapi\TupBayiProje.Moduller.Tenancy.Altyapi.csproj" />
  </ItemGroup>
</Project>
