<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TupBayiProje.Moduller.Tenancy.Uygulama</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/TupBayiProje.Moduller.Tenancy.Domain.csproj" />
    <ProjectReference Include="../Sozlesmeler/TupBayiProje.Moduller.Tenancy.Sozlesmeler.csproj" />
  </ItemGroup>
</Project>
