// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TupBayiProje.Moduller.Tenancy.Altyapi;

#nullable disable

namespace TupBayiProje.Moduller.Tenancy.Altyapi.Migrations
{
    [DbContext(typeof(MasterVeritabaniBaglami))]
    [Migration("20261008000000_MasterTenantIlkSema")]
    partial class MasterTenantIlkSema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("master")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TupBayiProje.Moduller.Tenancy.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", "master");
                });

            modelBuilder.Entity("TupBayiProje.Moduller.Tenancy.Domain.TenantVeritabani", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_veritabani");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_veritabani_tenant_id");

                    b.ToTable("tenant_veritabani", "master");
                });

            modelBuilder.Entity("TupBayiProje.Moduller.Tenancy.Domain.TenantVeritabani", b =>
                {
                    b.HasOne("TupBayiProje.Moduller.Tenancy.Domain.Tenant", null)
                        .WithOne()
                        .HasForeignKey("TupBayiProje.Moduller.Tenancy.Domain.TenantVeritabani", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_veritabani_tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
