name: tup_design_system
description: Ortak tasarim tokenlari ve yeniden kullanilabilir Flutter bilesenleri.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.4
  flutter: ">=3.41.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
