/* tslint:disable */
/* eslint-disable */
/**
 * TupBayiProje HTTP API
 * TBP-21 contract temeli. Onayli endpoint\'ler kendi Jira islerinde eklenir.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DogrulamaDetayi
 */
export interface DogrulamaDetayi {
  /**
   *
   * @type {string}
   * @memberof DogrulamaDetayi
   */
  field: string;
  /**
   *
   * @type {string}
   * @memberof DogrulamaDetayi
   */
  code: string;
}

/**
 * Check if a given object implements the DogrulamaDetayi interface.
 */
export function instanceOfDogrulamaDetayi(
  value: object,
): value is DogrulamaDetayi {
  if (!("field" in value) || value["field"] === undefined) return false;
  if (!("code" in value) || value["code"] === undefined) return false;
  return true;
}

export function DogrulamaDetayiFromJSON(json: any): DogrulamaDetayi {
  return DogrulamaDetayiFromJSONTyped(json, false);
}

export function DogrulamaDetayiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DogrulamaDetayi {
  if (json == null) {
    return json;
  }
  return {
    field: json["field"],
    code: json["code"],
  };
}

export function DogrulamaDetayiToJSON(json: any): DogrulamaDetayi {
  return DogrulamaDetayiToJSONTyped(json, false);
}

export function DogrulamaDetayiToJSONTyped(
  value?: DogrulamaDetayi | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    field: value["field"],
    code: value["code"],
  };
}
