/* tslint:disable */
/* eslint-disable */
/**
 * TupBayiProje HTTP API
 * TBP-21 contract temeli. Onayli endpoint\'ler kendi Jira islerinde eklenir.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DogrulamaDetayi } from "./DogrulamaDetayi";
import {
  DogrulamaDetayiFromJSON,
  DogrulamaDetayiFromJSONTyped,
  DogrulamaDetayiToJSON,
  DogrulamaDetayiToJSONTyped,
} from "./DogrulamaDetayi";

/**
 *
 * @export
 * @interface Hata
 */
export interface Hata {
  /**
   *
   * @type {string}
   * @memberof Hata
   */
  code: string;
  /**
   *
   * @type {string}
   * @memberof Hata
   */
  message: string;
  /**
   *
   * @type {string}
   * @memberof Hata
   */
  traceId: string;
  /**
   *
   * @type {Array<DogrulamaDetayi>}
   * @memberof Hata
   */
  details?: Array<DogrulamaDetayi>;
}

/**
 * Check if a given object implements the Hata interface.
 */
export function instanceOfHata(value: object): value is Hata {
  if (!("code" in value) || value["code"] === undefined) return false;
  if (!("message" in value) || value["message"] === undefined) return false;
  if (!("traceId" in value) || value["traceId"] === undefined) return false;
  return true;
}

export function HataFromJSON(json: any): Hata {
  return HataFromJSONTyped(json, false);
}

export function HataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Hata {
  if (json == null) {
    return json;
  }
  return {
    code: json["code"],
    message: json["message"],
    traceId: json["traceId"],
    details:
      json["details"] == null
        ? undefined
        : (json["details"] as Array<any>).map(DogrulamaDetayiFromJSON),
  };
}

export function HataToJSON(json: any): Hata {
  return HataToJSONTyped(json, false);
}

export function HataToJSONTyped(
  value?: Hata | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value["code"],
    message: value["message"],
    traceId: value["traceId"],
    details:
      value["details"] == null
        ? undefined
        : (value["details"] as Array<any>).map(DogrulamaDetayiToJSON),
  };
}
