/* tslint:disable */
/* eslint-disable */
/**
 * TupBayiProje HTTP API
 * TBP-21 contract temeli. Onayli endpoint\'ler kendi Jira islerinde eklenir.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Sayfalama
 */
export interface Sayfalama {
  /**
   *
   * @type {number}
   * @memberof Sayfalama
   */
  page: number;
  /**
   *
   * @type {number}
   * @memberof Sayfalama
   */
  pageSize: number;
  /**
   *
   * @type {number}
   * @memberof Sayfalama
   */
  totalItems: number;
  /**
   *
   * @type {number}
   * @memberof Sayfalama
   */
  totalPages: number;
}

/**
 * Check if a given object implements the Sayfalama interface.
 */
export function instanceOfSayfalama(value: object): value is Sayfalama {
  if (!("page" in value) || value["page"] === undefined) return false;
  if (!("pageSize" in value) || value["pageSize"] === undefined) return false;
  if (!("totalItems" in value) || value["totalItems"] === undefined)
    return false;
  if (!("totalPages" in value) || value["totalPages"] === undefined)
    return false;
  return true;
}

export function SayfalamaFromJSON(json: any): Sayfalama {
  return SayfalamaFromJSONTyped(json, false);
}

export function SayfalamaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Sayfalama {
  if (json == null) {
    return json;
  }
  return {
    page: json["page"],
    pageSize: json["pageSize"],
    totalItems: json["totalItems"],
    totalPages: json["totalPages"],
  };
}

export function SayfalamaToJSON(json: any): Sayfalama {
  return SayfalamaToJSONTyped(json, false);
}

export function SayfalamaToJSONTyped(
  value?: Sayfalama | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    page: value["page"],
    pageSize: value["pageSize"],
    totalItems: value["totalItems"],
    totalPages: value["totalPages"],
  };
}
