/* tslint:disable */
/* eslint-disable */
/**
 * TupBayiProje HTTP API
 * TBP-21 contract temeli. Onayli endpoint\'ler kendi Jira islerinde eklenir.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SistemSaglik
 */
export interface SistemSaglik {
  /**
   *
   * @type {string}
   * @memberof SistemSaglik
   */
  status: SistemSaglikStatusEnum;
  /**
   *
   * @type {string}
   * @memberof SistemSaglik
   */
  service: string;
  /**
   *
   * @type {string}
   * @memberof SistemSaglik
   */
  apiVersion: string;
  /**
   *
   * @type {Date}
   * @memberof SistemSaglik
   */
  timestampUtc: Date;
  /**
   *
   * @type {string}
   * @memberof SistemSaglik
   */
  traceId: string;
}

/**
 * @export
 */
export const SistemSaglikStatusEnum = {
  Ok: "ok",
  UnknownDefaultOpenApi: "11184809",
} as const;
export type SistemSaglikStatusEnum =
  (typeof SistemSaglikStatusEnum)[keyof typeof SistemSaglikStatusEnum];

/**
 * Check if a given object implements the SistemSaglik interface.
 */
export function instanceOfSistemSaglik(value: object): value is SistemSaglik {
  if (!("status" in value) || value["status"] === undefined) return false;
  if (!("service" in value) || value["service"] === undefined) return false;
  if (!("apiVersion" in value) || value["apiVersion"] === undefined)
    return false;
  if (!("timestampUtc" in value) || value["timestampUtc"] === undefined)
    return false;
  if (!("traceId" in value) || value["traceId"] === undefined) return false;
  return true;
}

export function SistemSaglikFromJSON(json: any): SistemSaglik {
  return SistemSaglikFromJSONTyped(json, false);
}

export function SistemSaglikFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SistemSaglik {
  if (json == null) {
    return json;
  }
  return {
    status: json["status"],
    service: json["service"],
    apiVersion: json["apiVersion"],
    timestampUtc: new Date(json["timestampUtc"]),
    traceId: json["traceId"],
  };
}

export function SistemSaglikToJSON(json: any): SistemSaglik {
  return SistemSaglikToJSONTyped(json, false);
}

export function SistemSaglikToJSONTyped(
  value?: SistemSaglik | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value["status"],
    service: value["service"],
    apiVersion: value["apiVersion"],
    timestampUtc: value["timestampUtc"].toISOString(),
    traceId: value["traceId"],
  };
}
